apiVersion: v1
kind: Service
metadata:
  name: moomed-profilepictureservice
spec:
  clusterIP: None
  selector:
    name: moomed-profilepictureservice
  ports:
    - protocol: TCP
      port: 16422
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-profilepictureservice
  labels:
    name: moomed-profilepictureservice
spec:
  replicas: 3
  selector:  
    matchLabels:
      name: moomed-profilepictureservice
  template:
    metadata:
      labels:
        name: moomed-profilepictureservice
    spec:
      containers:
      - name: moomed-profilepictureservice
        image: moomed.azurecr.io/profilepictureservice
        ports:
        - containerPort: 80
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
      imagePullSecrets:
        - name: acrimgpullsecret