version: "3.4"

volumes:
  prometheus_db: {}
  grafana_db: {}

services:
  moomed.frontend:
    image: ${DOCKER_REGISTRY-}moomedfrontend
    build:
      context: .
      dockerfile: Services/MooMed.Frontend/Dockerfile
    labels:
      - moomedcompose
    ports:
      - "1337:80"
      - "1338:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=1338
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/localHttps/moomedLocalhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test!234
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs
      - ./Certs/localHttps:/localHttps

  moomed.sessionservice:
    image: ${DOCKER_REGISTRY-}moomedsessionservice
    build:
      context: .
      dockerfile: Services/MooMed.SessionService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.searchservice:
    image: ${DOCKER_REGISTRY-}moomedsearchservice
    build:
      context: .
      dockerfile: Services/MooMed.SearchService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.profilepictureservice:
    image: ${DOCKER_REGISTRY-}moomedprofilepictureservice
    build:
      context: .
      dockerfile: Services/MooMed.ProfilePictureService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.accountvalidationservice:
    image: ${DOCKER_REGISTRY-}moomedaccountvalidationservice
    build:
      context: .
      dockerfile: Services/MooMed.AccountValidationService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.accountservice:
    image: ${DOCKER_REGISTRY-}moomedaccountservice
    build:
      context: .
      dockerfile: Services/MooMed.AccountService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.financeservice:
    image: ${DOCKER_REGISTRY-}moomedfinanceservice
    build:
      context: .
      dockerfile: Services/MooMed.FinanceService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.rabbitmq:
    container_name: rabbitmq
    image: docker.io/library/rabbitmq:3.8.6-management
    labels:
      - moomedcompose
    ports:
      - "12643:15672"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    labels:
      - moomedcompose
    volumes:
      - ./General/Metrics/Prometheus/DockerCompose:/etc/prometheus
      - ./prometheus_db:/var/lib/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    labels:
      - moomedcompose
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

  moomed.redis:
    image: redis
    labels:
      - moomedcompose
    ports:
      - "6379:6379"

  moomed.chatservice:
    image: ${DOCKER_REGISTRY-}moomedchatservice
    build:
      context: .
      dockerfile: Services/MooMed.ChatService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs

  moomed.savingservice:
    image: ${DOCKER_REGISTRY-}moomedsavingservice
    build:
      context: .
      dockerfile: Services/MooMed.SavingService/Dockerfile
    labels:
      - moomedcompose
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./Logs:/hostlogs
