version: '3.4'

services:
  moomed.stateful.profilepictureservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44313
    ports:
      - "53458:80"
      - "44313:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  moomed.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

