version: '3.4'

volumes:
    prometheus_db: {}
    grafana_db: {}

services:

  moomed.frontend:
    image: ${DOCKER_REGISTRY-}moomedfrontend
    build:
      context: .
      dockerfile: Services/MooMed.Frontend/Dockerfile
    ports:
    - "1337:80"
    - "1338:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    volumes:
      - ./Logs:/hostlogs
 
  MooMed.sessionservice:
    image: ${DOCKER_REGISTRY-}moomedsessionservice
    build:
      context: .
      dockerfile: Services/MooMed.SessionService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
    - "2337:80"
    - "2338:443"
    volumes:
      - ./Logs:/hostlogs


  moomed.searchservice:
    image: ${DOCKER_REGISTRY-}moomedsearchservice
    build:
      context: .
      dockerfile: Services/MooMed.SearchService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs


  moomed.profilepictureservice:
    image: ${DOCKER_REGISTRY-}moomedprofilepictureservice
    build:
      context: .
      dockerfile: Services/MooMed.ProfilePictureService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs


  MooMed.accountvalidationservice:
    image: ${DOCKER_REGISTRY-}moomedaccountvalidationservice
    build:
      context: .
      dockerfile: Services/MooMed.AccountValidationService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs


  MooMed.accountservice:
    image: ${DOCKER_REGISTRY-}moomedaccountservice
    build:
      context: .
      dockerfile: Services/MooMed.AccountService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs


  moomed.financeservice:
    image: ${DOCKER_REGISTRY-}moomedfinanceservice
    build:
      context: .
      dockerfile: Services/MooMed.FinanceService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs

  moomed.rabbitmq:
    container_name: rabbitmq
    image: docker.io/library/rabbitmq:3.8.6-management
    ports:
    - "12643:15672"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
    - ./General/Metrics/Prometheus/DockerCompose:/etc/prometheus
    - ./prometheus_db:/var/lib/prometheus
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
    - ./grafana_db:/var/lib/grafana
    depends_on:
    - prometheus
    ports:
    - '3000:3000'

  moomed.redis:
    image: redis
    ports:
    - '6379:6379'

  moomed.chatservice:
    image: ${DOCKER_REGISTRY-}moomedchatservice
    build:
      context: .
      dockerfile: Services/MooMed.ChatService/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./Logs:/hostlogs


  moomed.monitoringservice:
    image: ${DOCKER_REGISTRY-}moomedmonitoring
    build:
      context: .
      dockerfile: Services/MooMed.Monitoring/Dockerfile
    healthcheck:
      test: curl --fail -s http://localhost/health/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
    - "4122:80"
    volumes:
      - ./Logs:/hostlogs