version: '3.4'

services:
  moomed.web:
    image: ${DOCKER_REGISTRY-}moomedweb
    build:
      context: .
      dockerfile: Services/MooMed/Dockerfile
    ports:
    - "1337:80"
    - "1338:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  moomed.stateful.sessionservice:
    image: ${DOCKER_REGISTRY-}moomedstatefulsessionservice
    build:
      context: .
      dockerfile: Services/MooMed.Stateful.SessionService/Dockerfile


  moomed.searchservice:
    image: ${DOCKER_REGISTRY-}moomedstatefulsearchservice
    build:
      context: .
      dockerfile: Services/MooMed.Stateful.SearchService/Dockerfile


  moomed.profilepictureservice:
    image: ${DOCKER_REGISTRY-}moomedstatefulprofilepictureservicekub
    build:
      context: .
      dockerfile: Services/MooMed.Stateful.ProfilePictureService/Dockerfile


  moomed.stateful.accountvalidationservice:
    image: ${DOCKER_REGISTRY-}moomedstatefulaccountvalidationservice
    build:
      context: .
      dockerfile: Services/MooMed.Stateful.AccountValidationService/Dockerfile


  moomed.stateful.accountservice:
    image: ${DOCKER_REGISTRY-}moomedstatefulaccountservice
    build:
      context: .
      dockerfile: Services/MooMed.Stateful.AccountService/Dockerfile


  moomed.financeservice:
    image: ${DOCKER_REGISTRY-}moomedfinanceservice
    build:
      context: .
      dockerfile: Services/MooMed.FinanceService/Dockerfile

  moomed.rabbitmq:
    container_name: rabbitmq
    image: docker.io/library/rabbitmq:3-management
    ports:
    - "12643:15672"

  moomed.chatservice:
    image: ${DOCKER_REGISTRY-}moomedchatservice
    build:
      context: .
      dockerfile: Services/MooMed.ChatService/Dockerfile


  moomed.monitoringservice:
    image: ${DOCKER_REGISTRY-}moomedmonitoring
    build:
      context: .
      dockerfile: Services/MooMed.Monitoring/Dockerfile
    ports:
    - "4122:80"