# Compose for local registry

version: "3.4"
services:
  docker-registry:
    image: registry:2
    container_name: kindRegistry
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
  docker-registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - "8086:80"
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=admin
    restart: always
    depends_on:
      - docker-registry
