apiVersion: v1
kind: Service
metadata:
  name: moomed-accountvalidationservice
spec:
  clusterIP: None
  ports:
    - name: http2
      port: 10042
      targetPort: 10042
      protocol: TCP
  selector:
    name: moomed-accountvalidationservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountvalidationservice
  labels:
    name: moomed-accountvalidationservice
spec:
  replicas: 3
  selector:
    matchLabels:
      name: moomed-accountvalidationservice
  template:
    metadata:
      labels:
        name: moomed-accountvalidationservice
        serviceType: moomedFunctionalService
    spec:
      containers:
        - name: moomed-accountvalidationservice
          image: moomed.azurecr.io/accountvalidationservice
          imagePullPolicy: Always
          ports:
            - containerPort: 10042
          env:
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: akv
                  key: client_secret
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
      imagePullSecrets:
        - name: acrimgpullsecret
