apiVersion: v1
kind: Service
metadata:
  name: moomed-redis
spec:
  clusterIP: None
  selector:
    name: moomed-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: moomed-redis
  template:
    metadata:
      name: moomed-redis
      labels:
        name: moomed-redis
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: moomed-redis
          image: docker.io/library/redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
