apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moomed-searchservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: 127.0.0.1:5000/searchservice
        name: moomed-searchservice