apiVersion: v1
kind: Service
metadata:
  name: moomed-sessionservice
spec:
  clusterIP: None
  ports:
    - name: http2
      port: 10042
      targetPort: 10042
      protocol: TCP
  selector:
    name: moomed-sessionservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-sessionservice
  labels:
    name: moomed-sessionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: moomed-sessionservice
  template:
    metadata:
      labels:
        name: moomed-sessionservice
        serviceType: moomedFunctionalService
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: moomed-sessionservice
          image: moomed.azurecr.io/sessionservice
          imagePullPolicy: Always
          ports:
            - containerPort: 10042
          env:
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: akv
                  key: client_secret
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
      imagePullSecrets:
        - name: acrimgpullsecret
