apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-profilepictureservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: moomed.azurecr.io/profilepictureservice:prod
          name: moomed-profilepictureservice
      imagePullSecrets:
        - name: acrimgpullsecret
