namespace MooMed.Common.Definitions.Models.User.ErrorCodes
{
	public enum IdentityErrorCode
	{
		Success,
		DefaultError,
		ConcurrencyFailure,
		PasswordMismatch,
		InvalidToken,
		LoginAlreadyAssociated,
		InvalidUserName,
		InvalidEmail,
		EmailMissing,
		DuplicateUserName,
		DuplicateEmail,
		InvalidRoleName,
		DuplicateRoleName,
		UserAlreadyHasPassword,
		UserLockoutNotEnabled,
		UserAlreadyInRole,
		UserNameNullOrEmpty,
		UserNotInRole,
		PasswordTooShort,
		PasswordRequiresNonAlphanumeric,
		PasswordRequiresDigit,
		PasswordRequiresLower,
		PasswordRequiresUpper,
		PasswordMissing,
		EmailNotConfirmed,
		EmailAlreadyConfirmed,
	}
}