global:
    scrape_interval: 5s
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: [
            'moomed.frontend',
            'moomed.monitoringservice',
            'moomed.stateful.sessionservice']
      metrics_path: /metrics-text