apiVersion: v1
kind: Service
metadata:
  name: moomed-accountservice
spec:
  clusterIP: None
  ports:
  - name: http2
    port: 10042
    targetPort: 10042
    protocol: TCP
  selector:
    name: moomed-accountservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountservice
spec:
  replicas: 3
  selector:
    matchLabels:
      name: moomed-accountservice
  template:
    metadata:
      labels:
        name: moomed-accountservice
        serviceType: moomedFunctionalService
    spec:
      containers:
      - image: moomed.azurecr.io/accountservice
        name: moomed-accountservice
        imagePullPolicy: Always
        ports:
        - name: http2
          containerPort: 10042
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 256Mi
      imagePullSecrets:
      - name: acrimgpullsecret
