apiVersion: v1
kind: Service
metadata:
  name: moomed-frontendservice
spec:
  type: LoadBalancer
  selector:
    name: moomed-frontendservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30522
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-frontendservice
spec:
  replicas: 2
  selector:
    matchLabels:
      name: moomed-frontendservice
  template:
    metadata:
      labels:
        name: moomed-frontendservice
    spec:
      containers:
      - name: moomed-frontendservice
        image: moomed.azurecr.io/frontendservice
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
      imagePullSecrets:
        - name: acrimgpullsecret