apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: moomed.azurecr.io/accountservice:prod
          name: moomed-accountservice
      imagePullSecrets:
        - name: acrimgpullsecret
