apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-financeservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: localhost:5000/financeservice:dev
          name: moomed-financeservice
