apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-financeservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: moomed.azurecr.io/financeservice:dev
        name: moomed-financeservice
      imagePullSecrets:
      - name: acrimgpullsecret