apiVersion: v1
kind: Service
metadata:
  name: moomed-profilepictureservice
spec:
  clusterIP: None
  ports:
  - name: http2
    port: 10042
    targetPort: 10042
    protocol: TCP
  selector:
    name: moomed-profilepictureservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-profilepictureservice
  labels:
    name: moomed-profilepictureservice
spec:
  replicas: 3
  selector:  
    matchLabels:
      name: moomed-profilepictureservice
  template:
    metadata:
      labels:
        name: moomed-profilepictureservice
        serviceType: moomedFunctionalService
    spec:
      containers:
      - name: moomed-profilepictureservice
        image: moomed.azurecr.io/profilepictureservice
        imagePullPolicy: Always
        ports:
        - containerPort: 10042
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 256Mi
      imagePullSecrets:
        - name: acrimgpullsecret