apiVersion: v1
kind: Service
metadata:
  name: moomed-monitoringservice
spec:
  clusterIP: None
  ports:
  - name: http2
    port: 10042
    targetPort: 10042
    protocol: TCP
  selector:
    name: moomed-monitoringservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-monitoringservice
  labels:
    name: moomed-monitoringservice
spec:
  replicas: 2
  selector:  
    matchLabels:
      name: moomed-monitoringservice
  template:
    metadata:
      labels:
        name: moomed-monitoringservice
    spec:
      containers:
      - name: moomed-monitoringservice
        image: moomed.azurecr.io/monitoringservice
        imagePullPolicy: Always
        ports:
        - containerPort: 10042
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
      imagePullSecrets:
        - name: acrimgpullsecret
