apiVersion: v1
kind: Service
metadata:
  name: moomed-searchservice
spec:
  clusterIP: None
  selector:
    name: moomed-searchservice
  ports:
    - protocol: TCP
      port: 16756
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-searchservice
  labels:
    name: moomed-searchservice
spec:
  replicas: 3
  selector:  
    matchLabels:
      name: moomed-searchservice
  template:
    metadata:
      labels:
        name: moomed-searchservice
    spec:
      containers:
      - name: moomed-searchservice
        image: moomed.azurecr.io/searchservice
        ports:
        - containerPort: 80
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
      imagePullSecrets:
        - name: acrimgpullsecret
