apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountvalidationservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: localhost:5000/accountvalidationservice:dev
          name: moomed-accountvalidationservice
