apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moomed-accountvalidationservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: moomed.azurecr.io/accountvalidationservice:dev
        name: moomed-accountvalidationservice
      imagePullSecrets:
      - name: acrimgpullsecret