apiVersion: v1
kind: Service
metadata:
  name: moomed-accountservice
spec:
  clusterIP: None
  selector:
    name: moomed-accountservice
  ports:
    - protocol: TCP
      port: 23523
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moomed-accountservice
spec:
  serviceName: moomed-accountservice
  replicas: 3
  selector:  
    matchLabels:
      name: moomed-accountservice
  template:
    metadata:
      labels:
        name: moomed-accountservice
    spec:
      containers:
      - name: moomed-accountservice
        image: moomed.azurecr.io/accountservice
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acrimgpullsecret
