apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-savingservice
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: moomed.azurecr.io/savingservice:dev
        name: moomed-savingservice
      imagePullSecrets:
      - name: acrimgpullsecret