apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-frontendservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: localhost:5000/frontendservice:dev
          name: moomed-frontendservice
