apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountvalidationservice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: moomed.azurecr.io/accountvalidationservice:prod
        name: moomed-accountvalidationservice
      imagePullSecrets:
      - name: acrimgpullsecret