apiVersion: v1
kind: Service
metadata:
  name: moomed-accountservice
spec:
  clusterIP: None
  ports:
  - port: 23523
    protocol: TCP
  selector:
    name: moomed-accountservice
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moomed-accountservice
spec:
  replicas: 3
  selector:
    matchLabels:
      name: moomed-accountservice
  serviceName: moomed-accountservice
  template:
    metadata:
      labels:
        name: moomed-accountservice
    spec:
      containers:
      - image: moomed.azurecr.io/accountservice
        imagePullPolicy: Always
        name: moomed-accountservice
        ports:
        - containerPort: 80
        env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: akv
                key: client_secret
      imagePullSecrets:
      - name: acrimgpullsecret
