apiVersion: apps/v1
kind: Deployment
metadata:
  name: moomed-accountservice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: localhost:5000/accountservice:dev
          name: moomed-accountservice
