//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 09-Dec-20 21:37:24
//----------------------

namespace MooMed.RemotingProxies.Proxies
{
	public class AccountValidationServiceProxy : MooMed.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<MooMed.ServiceBase.Services.Interface.IAccountValidationService>, MooMed.ServiceBase.Services.Interface.IAccountValidationService
	{
		public AccountValidationServiceProxy(MooMed.IPC.Grpc.Interface.IGrpcClientProvider clientProvider)
			: base(clientProvider,
				MooMed.Common.Definitions.IPC.DeploymentService.AccountValidationService)
		{ }

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse<MooMed.Common.Definitions.Models.User.ErrorCodes.IdentityErrorCode>> ValidateRegistration(
			MooMed.Common.Definitions.Models.User.AccountValidationModel accountValidationModel)
			=> InvokeWithResult(service => service.ValidateRegistration(
				accountValidationModel));

	}
}
