//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 09-Dec-20 21:37:24
//----------------------

namespace MooMed.RemotingProxies.Proxies
{
    public class ChatServiceProxy : MooMed.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<MooMed.ServiceBase.Services.Interface.IChatService>, MooMed.ServiceBase.Services.Interface.IChatService
    {
        public ChatServiceProxy(MooMed.IPC.Grpc.Interface.IGrpcClientProvider clientProvider)
            : base(clientProvider,
                MooMed.Common.Definitions.IPC.DeploymentService.ChatService)
        { }

        public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse<MooMed.Common.Definitions.Models.Chat.RetrievedMessages>> GetMessages(
            MooMed.Common.Definitions.Models.Chat.GetMessages getMessages)
            => InvokeWithResult(service => service.GetMessages(
                getMessages));

        public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse> SendMessage(
            MooMed.Common.Definitions.Models.Chat.SendMessage sendMessage)
            => InvokeWithResult(service => service.SendMessage(
                sendMessage));
    }
}