//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 09-Dec-20 21:37:24
//----------------------

namespace MooMed.RemotingProxies.Proxies
{
	public class FinanceServiceProxy : MooMed.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<MooMed.ServiceBase.Services.Interface.IFinanceService>, MooMed.ServiceBase.Services.Interface.IFinanceService
	{
		public FinanceServiceProxy(MooMed.IPC.Grpc.Interface.IGrpcClientProvider clientProvider)
			: base(clientProvider,
				MooMed.Common.Definitions.IPC.DeploymentService.FinanceService)
		{ }

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse<System.Collections.Generic.IEnumerable<MooMed.Common.Definitions.Models.Finance.ExchangeTraded>>> GetExchangeTradeds()
			=> InvokeWithResult(service => service.GetExchangeTradeds());

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse<MooMed.Common.Definitions.Models.Portfolio.Portfolio>> GetPortfolio(
			MooMed.Common.Definitions.Models.Session.Interface.ISessionContext sessionContext)
			=> InvokeWithResult(service => service.GetPortfolio(
				sessionContext));

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse> AddFondToPortfolio(
			MooMed.Common.Definitions.Models.Portfolio.PortfolioItem portfolioItem)
			=> InvokeWithResult(service => service.AddFondToPortfolio(
				portfolioItem));

	}
}
