//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 23-Nov-20 19:16:58
//----------------------

namespace MooMed.RemotingProxies.Proxies
{
	public class MonitoringServiceProxy : MooMed.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<MooMed.ServiceBase.Services.Interface.IMonitoringService>, MooMed.ServiceBase.Services.Interface.IMonitoringService
	{
		public MonitoringServiceProxy(MooMed.IPC.Grpc.Interface.IGrpcClientProvider clientProvider)
			: base(clientProvider,
				MooMed.Common.Definitions.IPC.DeploymentService.MonitoringService)
		{ }

	}
}
