//----------------------
//This file was autogenerated by GrpcProxyGenerator.Service.GrpcProxyFactory
//Timestamp of generation: UTC 09-Dec-20 21:37:24
//----------------------

namespace MooMed.RemotingProxies.Proxies
{
	public class SavingServiceProxy : MooMed.RemotingProxies.ProxyInvocation.AbstractDeploymentProxy<MooMed.ServiceBase.Services.Interface.ISavingService>, MooMed.ServiceBase.Services.Interface.ISavingService
	{
		public SavingServiceProxy(MooMed.IPC.Grpc.Interface.IGrpcClientProvider clientProvider)
			: base(clientProvider,
				MooMed.Common.Definitions.IPC.DeploymentService.SavingService)
		{ }

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse> SetCurrency(
			MooMed.Common.Definitions.Models.Saving.SetCurrencyModel setCurrencyModel)
			=> InvokeWithResult(service => service.SetCurrency(
				setCurrencyModel));

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse> SetAssets(
			MooMed.Common.Definitions.Models.Saving.AssetsModel assetsModel)
			=> InvokeWithResult(service => service.SetAssets(
				assetsModel));

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse> SetCashFlowItems(
			MooMed.Common.Definitions.Models.Saving.SetCashFlowItemsModel setCashFlowItemsModel)
			=> InvokeWithResult(service => service.SetCashFlowItems(
				setCashFlowItemsModel));

		public System.Threading.Tasks.Task<MooMed.Core.DataTypes.ServiceResponse<MooMed.Common.Definitions.Models.Saving.SavingInfoModel>> GetSavingInformation(
			MooMed.Common.Definitions.Models.Session.Interface.ISessionContext sessionContext)
			=> InvokeWithResult(service => service.GetSavingInformation(
				sessionContext));

	}
}
